version: '3.9'
services:
  readme.account.mongo:
    image: mongo:4.4
    container_name: readme.account.mongo
    restart: always
    volumes:
      - readme.account.mongo.volume:/data/db
    env_file:
      - .readme.account.mongodb.env
    networks:
      - readme.account.network

  readme.account:
    depends_on:
      - readme.account.mongo
    container_name: readme.account.app
    image: ghcr.io/alexandr10m/readme.api:1.0.0
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - .readme.account.env
    networks:
      - readme.account.network

volumes:
  readme.account.mongo.volume: {}

networks:
  readme.account.network:
    driver: bridge
